services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=internshiptracker'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=internshiptracker'
    ports:
      - '5432'
