services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=internshiptracker'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=internshiptracker'
    ports:
      - '5432'

  mailpit:
    image: 'axllent/mailpit:v1.31.4'
    ports:
      - '1025:1025'
      - '8025:8025'
